// <auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace DB.Migrations
{
    /// <inheritdoc />
    public partial class health_group_teacher : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<string>(
                name: "HealthGroupTeacherId",
                table: "Students",
                type: "character varying(36)",
                maxLength: 36,
                nullable: true);

            migrationBuilder.CreateIndex(
                name: "IX_Students_HealthGroupTeacherId",
                table: "Students",
                column: "HealthGroupTeacherId");

            migrationBuilder.AddForeignKey(
                name: "FK_Students_Teachers_HealthGroupTeacherId",
                table: "Students",
                column: "HealthGroupTeacherId",
                principalTable: "Teachers",
                principalColumn: "TeacherGuid");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_Students_Teachers_HealthGroupTeacherId",
                table: "Students");

            migrationBuilder.DropIndex(
                name: "IX_Students_HealthGroupTeacherId",
                table: "Students");

            migrationBuilder.DropColumn(
                name: "HealthGroupTeacherId",
                table: "Students");
        }
    }
}
