// <auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace DB.Migrations
{
    /// <inheritdoc />
    public partial class better_histories_naming : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_PointsStudentsHistory_Students_StudentGuid",
                table: "PointsStudentsHistory");

            migrationBuilder.DropForeignKey(
                name: "FK_PointsStudentsHistory_Teachers_TeacherGuid",
                table: "PointsStudentsHistory");

            migrationBuilder.DropForeignKey(
                name: "FK_StandardsStudentsHistory_Students_StudentGuid",
                table: "StandardsStudentsHistory");

            migrationBuilder.DropForeignKey(
                name: "FK_StandardsStudentsHistory_Teachers_TeacherGuid",
                table: "StandardsStudentsHistory");

            migrationBuilder.DropForeignKey(
                name: "FK_VisitsStudentsHistory_Students_StudentGuid",
                table: "VisitsStudentsHistory");

            migrationBuilder.DropForeignKey(
                name: "FK_VisitsStudentsHistory_Teachers_TeacherGuid",
                table: "VisitsStudentsHistory");

            migrationBuilder.DropPrimaryKey(
                name: "PK_VisitsStudentsHistory",
                table: "VisitsStudentsHistory");

            migrationBuilder.DropPrimaryKey(
                name: "PK_StandardsStudentsHistory",
                table: "StandardsStudentsHistory");

            migrationBuilder.DropPrimaryKey(
                name: "PK_PointsStudentsHistory",
                table: "PointsStudentsHistory");

            migrationBuilder.RenameTable(
                name: "VisitsStudentsHistory",
                newName: "VisitsHistory");

            migrationBuilder.RenameTable(
                name: "StandardsStudentsHistory",
                newName: "StandardsHistory");

            migrationBuilder.RenameTable(
                name: "PointsStudentsHistory",
                newName: "PointsHistory");

            migrationBuilder.RenameIndex(
                name: "IX_VisitsStudentsHistory_TeacherGuid",
                table: "VisitsHistory",
                newName: "IX_VisitsHistory_TeacherGuid");

            migrationBuilder.RenameIndex(
                name: "IX_VisitsStudentsHistory_StudentGuid",
                table: "VisitsHistory",
                newName: "IX_VisitsHistory_StudentGuid");

            migrationBuilder.RenameIndex(
                name: "IX_StandardsStudentsHistory_TeacherGuid",
                table: "StandardsHistory",
                newName: "IX_StandardsHistory_TeacherGuid");

            migrationBuilder.RenameIndex(
                name: "IX_StandardsStudentsHistory_StudentGuid",
                table: "StandardsHistory",
                newName: "IX_StandardsHistory_StudentGuid");

            migrationBuilder.RenameIndex(
                name: "IX_PointsStudentsHistory_TeacherGuid",
                table: "PointsHistory",
                newName: "IX_PointsHistory_TeacherGuid");

            migrationBuilder.RenameIndex(
                name: "IX_PointsStudentsHistory_StudentGuid",
                table: "PointsHistory",
                newName: "IX_PointsHistory_StudentGuid");

            migrationBuilder.AddPrimaryKey(
                name: "PK_VisitsHistory",
                table: "VisitsHistory",
                column: "Id");

            migrationBuilder.AddPrimaryKey(
                name: "PK_StandardsHistory",
                table: "StandardsHistory",
                column: "Id");

            migrationBuilder.AddPrimaryKey(
                name: "PK_PointsHistory",
                table: "PointsHistory",
                column: "Id");

            migrationBuilder.AddForeignKey(
                name: "FK_PointsHistory_Students_StudentGuid",
                table: "PointsHistory",
                column: "StudentGuid",
                principalTable: "Students",
                principalColumn: "StudentGuid",
                onDelete: ReferentialAction.Cascade);

            migrationBuilder.AddForeignKey(
                name: "FK_PointsHistory_Teachers_TeacherGuid",
                table: "PointsHistory",
                column: "TeacherGuid",
                principalTable: "Teachers",
                principalColumn: "TeacherGuid",
                onDelete: ReferentialAction.Cascade);

            migrationBuilder.AddForeignKey(
                name: "FK_StandardsHistory_Students_StudentGuid",
                table: "StandardsHistory",
                column: "StudentGuid",
                principalTable: "Students",
                principalColumn: "StudentGuid",
                onDelete: ReferentialAction.Cascade);

            migrationBuilder.AddForeignKey(
                name: "FK_StandardsHistory_Teachers_TeacherGuid",
                table: "StandardsHistory",
                column: "TeacherGuid",
                principalTable: "Teachers",
                principalColumn: "TeacherGuid",
                onDelete: ReferentialAction.Cascade);

            migrationBuilder.AddForeignKey(
                name: "FK_VisitsHistory_Students_StudentGuid",
                table: "VisitsHistory",
                column: "StudentGuid",
                principalTable: "Students",
                principalColumn: "StudentGuid",
                onDelete: ReferentialAction.Cascade);

            migrationBuilder.AddForeignKey(
                name: "FK_VisitsHistory_Teachers_TeacherGuid",
                table: "VisitsHistory",
                column: "TeacherGuid",
                principalTable: "Teachers",
                principalColumn: "TeacherGuid",
                onDelete: ReferentialAction.Cascade);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_PointsHistory_Students_StudentGuid",
                table: "PointsHistory");

            migrationBuilder.DropForeignKey(
                name: "FK_PointsHistory_Teachers_TeacherGuid",
                table: "PointsHistory");

            migrationBuilder.DropForeignKey(
                name: "FK_StandardsHistory_Students_StudentGuid",
                table: "StandardsHistory");

            migrationBuilder.DropForeignKey(
                name: "FK_StandardsHistory_Teachers_TeacherGuid",
                table: "StandardsHistory");

            migrationBuilder.DropForeignKey(
                name: "FK_VisitsHistory_Students_StudentGuid",
                table: "VisitsHistory");

            migrationBuilder.DropForeignKey(
                name: "FK_VisitsHistory_Teachers_TeacherGuid",
                table: "VisitsHistory");

            migrationBuilder.DropPrimaryKey(
                name: "PK_VisitsHistory",
                table: "VisitsHistory");

            migrationBuilder.DropPrimaryKey(
                name: "PK_StandardsHistory",
                table: "StandardsHistory");

            migrationBuilder.DropPrimaryKey(
                name: "PK_PointsHistory",
                table: "PointsHistory");

            migrationBuilder.RenameTable(
                name: "VisitsHistory",
                newName: "VisitsStudentsHistory");

            migrationBuilder.RenameTable(
                name: "StandardsHistory",
                newName: "StandardsStudentsHistory");

            migrationBuilder.RenameTable(
                name: "PointsHistory",
                newName: "PointsStudentsHistory");

            migrationBuilder.RenameIndex(
                name: "IX_VisitsHistory_TeacherGuid",
                table: "VisitsStudentsHistory",
                newName: "IX_VisitsStudentsHistory_TeacherGuid");

            migrationBuilder.RenameIndex(
                name: "IX_VisitsHistory_StudentGuid",
                table: "VisitsStudentsHistory",
                newName: "IX_VisitsStudentsHistory_StudentGuid");

            migrationBuilder.RenameIndex(
                name: "IX_StandardsHistory_TeacherGuid",
                table: "StandardsStudentsHistory",
                newName: "IX_StandardsStudentsHistory_TeacherGuid");

            migrationBuilder.RenameIndex(
                name: "IX_StandardsHistory_StudentGuid",
                table: "StandardsStudentsHistory",
                newName: "IX_StandardsStudentsHistory_StudentGuid");

            migrationBuilder.RenameIndex(
                name: "IX_PointsHistory_TeacherGuid",
                table: "PointsStudentsHistory",
                newName: "IX_PointsStudentsHistory_TeacherGuid");

            migrationBuilder.RenameIndex(
                name: "IX_PointsHistory_StudentGuid",
                table: "PointsStudentsHistory",
                newName: "IX_PointsStudentsHistory_StudentGuid");

            migrationBuilder.AddPrimaryKey(
                name: "PK_VisitsStudentsHistory",
                table: "VisitsStudentsHistory",
                column: "Id");

            migrationBuilder.AddPrimaryKey(
                name: "PK_StandardsStudentsHistory",
                table: "StandardsStudentsHistory",
                column: "Id");

            migrationBuilder.AddPrimaryKey(
                name: "PK_PointsStudentsHistory",
                table: "PointsStudentsHistory",
                column: "Id");

            migrationBuilder.AddForeignKey(
                name: "FK_PointsStudentsHistory_Students_StudentGuid",
                table: "PointsStudentsHistory",
                column: "StudentGuid",
                principalTable: "Students",
                principalColumn: "StudentGuid",
                onDelete: ReferentialAction.Cascade);

            migrationBuilder.AddForeignKey(
                name: "FK_PointsStudentsHistory_Teachers_TeacherGuid",
                table: "PointsStudentsHistory",
                column: "TeacherGuid",
                principalTable: "Teachers",
                principalColumn: "TeacherGuid",
                onDelete: ReferentialAction.Cascade);

            migrationBuilder.AddForeignKey(
                name: "FK_StandardsStudentsHistory_Students_StudentGuid",
                table: "StandardsStudentsHistory",
                column: "StudentGuid",
                principalTable: "Students",
                principalColumn: "StudentGuid",
                onDelete: ReferentialAction.Cascade);

            migrationBuilder.AddForeignKey(
                name: "FK_StandardsStudentsHistory_Teachers_TeacherGuid",
                table: "StandardsStudentsHistory",
                column: "TeacherGuid",
                principalTable: "Teachers",
                principalColumn: "TeacherGuid",
                onDelete: ReferentialAction.Cascade);

            migrationBuilder.AddForeignKey(
                name: "FK_VisitsStudentsHistory_Students_StudentGuid",
                table: "VisitsStudentsHistory",
                column: "StudentGuid",
                principalTable: "Students",
                principalColumn: "StudentGuid",
                onDelete: ReferentialAction.Cascade);

            migrationBuilder.AddForeignKey(
                name: "FK_VisitsStudentsHistory_Teachers_TeacherGuid",
                table: "VisitsStudentsHistory",
                column: "TeacherGuid",
                principalTable: "Teachers",
                principalColumn: "TeacherGuid",
                onDelete: ReferentialAction.Cascade);
        }
    }
}
