version: "2.2"

services:
  physedjournal:
    image: "ghcr.io/pritexx/physedjournal:${IMAGE_TAG}"
    restart: always
    container_name: physedjournal
    env_file:
      - .env.secret
        
  admin-api:
    image: "ghcr.io/pritexx/physedjournal:${IMAGE_TAG}-admin-api"
    restart: always
    container_name: phys-admin-api
    env_file:
      - .env.secret
        
  admin-ui:
    image: "ghcr.io/pritexx/physedjournal:${IMAGE_TAG}-admin-ui"
    restart: always
    container_name: phys-admin-ui
    env_file:
      - .env.secret

  seq:
    image: datalust/seq:2024.3
    container_name: phys-seq
    restart: always
    volumes:
      - seq-data:/data
    environment:
      ACCEPT_EULA: "Y"
  
  grafana:
    image: grafana/grafana:9.5.6
    volumes:
      - grafana-data:/var/lib/grafana
    container_name: grafana
    restart: always
    environment:
      GF_SERVER_ROOT_URL: "%(protocol)s://%(domain)s:%(http_port)s/physedjournal/grafana/"
      GF_SERVER_SERVE_FROM_SUB_PATH: "true"
  
  nginx:
    image: nginx:1.23
    container_name: nginx
    restart: always
    ports:
      - "8448:80"
      - "8449:443"
    depends_on:
      - physedjournal
    volumes:
      - /cert:/cert:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

volumes:
  grafana-data:
    driver: local
  seq-data:
    driver: local    