name: Deploy to server

on:
  workflow_dispatch: 

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  USERNAME: admin2
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    permissions:
      contents: read
      packages: write
    steps:
      - name: Extract specified tag
        run: |
          echo "IMAGE_TAG=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV
        
      - name: Put secrets in env
        uses: oNaiPs/secrets-to-env-action@v1
        with: 
          secrets: ${{toJson(secrets)}}
          
      - name: Checkout
        uses: actions/checkout@v3
          
      - name: Create secret env file
        run: |
          envsubst < deploy/.env.template > deploy/.env.secret
          envsubst < deploy/.env.stage.template > deploy/.env.stage.secret

      - name: Tar deploy folder
        run: tar -cvf deploy.tar deploy/
      
      - name: Install OpenVPN
        run: |
          sudo apt update
          sudo apt install -y openvpn openvpn-systemd-resolved     

      - name: Setup VPN config
        run: echo "${{ secrets.OVPN_FILE }}" > config.ovpn

      - name: Connect to VPN
        uses: "kota65535/github-openvpn-connect-action@v2"
        with:
          config_file: config.ovpn
          username: ${{secrets.OVPN_USERNAME}}
          password: ${{secrets.OVPN_PASSWORD}}

      - name: Copy deploy.tar
        uses: appleboy/scp-action@master
        with:
          host: ${{secrets.HOST}}
          username: ${{env.USERNAME}}
          password: ${{ secrets.HOST_PASSWORD }}
          source: "deploy.tar"
          target: "/home/${{env.USERNAME}}/physedjournal"

      - name: Pull and run containers
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{secrets.HOST}}
          username: ${{ env.USERNAME }}
          password: ${{ secrets.HOST_PASSWORD }}
          script: |
            cd /home/${{env.USERNAME}}/physedjournal
            tar -xf deploy.tar -C /home/${{env.USERNAME}}/physedjournal
            cd deploy
            IMAGE_TAG=${{env.IMAGE_TAG}} docker-compose pull
            IMAGE_TAG=${{env.IMAGE_TAG}} docker-compose -p physedjournal up -d
            rm -r /home/${{env.USERNAME}}/physedjournal