name: Deploy to server

on:
  workflow_dispatch: 

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  USERNAME: admin2
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    permissions:
      contents: read
      packages: write
    steps:
      - name: Test
        run: |
          echo '$HOST_PASSWORD' | envsubst > test.txt
          cat test.txt
#      - name: Checkout
#        uses: actions/checkout@v3
#
#      - name: Install OpenVPN
#        run: |
#          sudo apt update
#          sudo apt install -y openvpn openvpn-systemd-resolved     
#
#      - name: Setup VPN config
#        run: echo "${{ secrets.OVPN_FILE }}" > config.ovpn
#
#      - name: Connect to VPN
#        uses: "kota65535/github-openvpn-connect-action@v2"
#        with:
#          config_file: config.ovpn
#          username: ${{secrets.OVPN_USERNAME}}
#          password: ${{secrets.OVPN_PASSWORD}}
#
#      - name: Copy docker-compose
#        uses: appleboy/scp-action@master
#        with:
#          host: ${{secrets.HOST}}
#          username: ${{env.USERNAME}}
#          password: ${{ secrets.HOST_PASSWORD }}
#          source: "docker-compose.yml"
#          target: "/home/${{env.USERNAME}}/physedjournal"
#
#      - name: Pull and run containers
#        uses: appleboy/ssh-action@v0.1.7
#        with:
#          host: ${{secrets.HOST}}
#          username: ${{ env.USERNAME }}
#          password: ${{ secrets.HOST_PASSWORD }}
#          script: |
#            cd /home/${{env.USERNAME}}/physedjournal
#            echo "${{secrets.ENV_FILE}}" > .env
#            docker-compose pull
#            docker-compose --env-file .env up -d
#            rm -r /home/${{env.USERNAME}}/physedjournal