#name: Build and push docker image
#
#on: 
#  push:
#    tags:
#      - "v[0-9]+.[0-9]+.[0-9]+"
#    
#env:
#  REGISTRY: ghcr.io
#  IMAGE_NAME: ${{ github.repository }}
#
#jobs:
#  build-and-push-image:
#    runs-on: ubuntu-latest
#    if: startsWith(github.ref, 'refs/tags/v')
#    permissions:
#      contents: read
#      packages: write
#
#    steps:
#      - name: Checkout repository
#        uses: actions/checkout@v3
#
#      - name: Log in to the Container registry
#        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
#        with:
#          registry: ${{ env.REGISTRY }}
#          username: ${{ github.actor }}
#          password: ${{ secrets.GITHUB_TOKEN }}
#          
#      - name: Extract tags for image
#        run: |
#          TAG=${GITHUB_REF#refs/tags/v}
#          VERSIONS=(${TAG//./ })
#          SHORT_TAG=${VERSIONS[0]}.${VERSIONS[1]}
#          echo "IMAGE_TAGS='\"${TAG};${SHORT_TAG};latest\"'" >> $GITHUB_ENV
#          
#      - name: Build and push Docker image
#        run: dotnet publish --os linux --arch x64 -c Release -p PublishProfile=DefaultContainer -p ContainerRegistry=${{ env.REGISTRY }} -p ContainerRepository=${{ env.IMAGE_NAME }} -p ContainerImageTags=${{ env.IMAGE_TAGS }}
#        