name: Build and push docker images

on: 
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-app:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract tags for image
        run: |
          TAG=${GITHUB_REF#refs/tags/v}
          echo "IMAGE_TAGS='\"${TAG};latest\"'" >> $GITHUB_ENV

      - name: Build and push Docker image
        run: dotnet publish ./PhysEdJournal.Api/PhysEdJournal.Api.csproj --os linux --arch x64 -c Release -p PublishProfile=DefaultContainer -p ContainerRegistry=${{ env.REGISTRY }} -p ContainerRepository=${{ env.IMAGE_NAME }} -p ContainerImageTags=${{ env.IMAGE_TAGS }}
  
  build-admin-api:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract tags for image
        run: |
          TAG=${GITHUB_REF#refs/tags/v}
          echo "IMAGE_TAGS='\"${TAG}-admin-api\"'" >> $GITHUB_ENV

      - name: Build and push Docker image
        run: dotnet publish ./Admin.Api/Admin.Api.csproj --os linux --arch x64 -c Release -p PublishProfile=DefaultContainer -p ContainerRegistry=${{ env.REGISTRY }} -p ContainerRepository=${{ env.IMAGE_NAME }} -p ContainerImageTags=${{ env.IMAGE_TAGS }}
        
  build-admin-ui:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract tags for image
        run: |
          TAG=${GITHUB_REF#refs/tags/v}
          echo "IMAGE_TAGS=${{env.REGISTRY}}/${{env.IMAGE_NAME}}:${TAG}-admin-ui" >> $GITHUB_ENV

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: ./Admin.UI
          push: true
          tags: ${{ env.IMAGE_TAGS }}